"""Type stubs for the micropy API - IDE/type-checker support only.

This file is never uploaded to the Arduino and is never imported while
compiling.  Run ``micropy init`` to copy it into a project next to
``pyrightconfig.json`` and ``main.py``; VS Code / Pylance then
complete the constants and functions below without any import.

``micropy stubs`` copies the very same file for older projects, which
can still add::

    from micropy_api import *
"""

from typing import Any

# --- digital and analog constants ------------------------------------------
OUTPUT: int
INPUT: int
INPUT_PULLUP: int
INPUT_PULLDOWN: int
HIGH: int
LOW: int
CHANGE: int
RISING: int
FALLING: int
LED_BUILTIN: int
A0: int
A1: int
A2: int
A3: int
A4: int
A5: int

# --- digital and analog I/O ------------------------------------------------
def pin_mode(pin: int, mode: int) -> None: ...
def digital_write(pin: int, value: int) -> None: ...
def digital_read(pin: int) -> int: ...
def analog_read(pin: int) -> int: ...
def analog_write(pin: int, value: int) -> None: ...

# --- timing ----------------------------------------------------------------
def delay(milliseconds: int) -> None: ...
def delay_microseconds(microseconds: int) -> None: ...
def millis() -> int: ...
def micros() -> int: ...

# --- serial ----------------------------------------------------------------
def serial_begin(baud: int) -> None: ...
def serial_end() -> None: ...
def serial_flush() -> None: ...
def serial_available() -> int: ...
def serial_read() -> int: ...
def serial_print(value: Any, format: int = ...) -> None: ...
def serial_println(value: Any = ..., format: int = ...) -> None: ...

# --- Arduino's String class ------------------------------------------------
class String:
    def __init__(self, value: Any = ...) -> None: ...
    def length(self) -> int: ...
    def charAt(self, index: int) -> str: ...

# --- math helpers (Arduino maps these onto the C++ standard library) -------
def abs(value: int) -> int: ...
def min(a: int, b: int) -> int: ...
def max(a: int, b: int) -> int: ...
def constrain(value: int, low: int, high: int) -> int: ...
def pow(base: float, exponent: float) -> float: ...
def sqrt(value: float) -> float: ...
def floor(value: float) -> float: ...
def ceil(value: float) -> float: ...
def round(value: float) -> float: ...

# --- Arduino libraries (``from micropy import Servo``) ---------------------
class Servo:
    def attach(self, pin: int) -> None: ...
    def detach(self) -> None: ...
    def write(self, angle: int) -> None: ...
    def read(self) -> int: ...
